# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=5, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='user',
            name='link1',
            field=models.SlugField(blank=True, verbose_name='link one'),
        ),
        migrations.AddField(
            model_name='user',
            name='link1txt',
            field=models.CharField(blank=True, max_length=12, verbose_name='link one text'),
        ),
        migrations.AddField(
            model_name='user',
            name='link2',
            field=models.SlugField(blank=True, verbose_name='link two'),
        ),
        migrations.AddField(
            model_name='user',
            name='link2txt',
            field=models.CharField(blank=True, max_length=12, verbose_name='link two text'),
        ),
        migrations.AddField(
            model_name='user',
            name='link3',
            field=models.SlugField(blank=True, verbose_name='link three'),
        ),
        migrations.AddField(
            model_name='user',
            name='link3txt',
            field=models.CharField(blank=True, max_length=12, verbose_name='link three text'),
        ),
    ]
