# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170526_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('zh-hans', 'Chinese')], max_length=7, verbose_name='language'),
        ),
    ]
