# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170526_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
    ]
