# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 02:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_auto_20170509_0623'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('work_type', models.CharField(choices=[('MECH', 'Mechanical'), ('ELEC', 'Electronic'), ('ASSM', 'Assembly')], max_length=3)),
                ('status', models.CharField(choices=[('INP', 'In-Progress'), ('HLD', 'On Hold'), ('CND', 'Cancelled'), ('CMP', 'Completed')], max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Customer')),
                ('engineer', models.ManyToManyField(to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('WCUST', 'Waiting for Customer Response'), ('MKDFM', 'Creating DFM'), ('TLDSN', 'Tooling Design'), ('TLBLD', 'Tooling Build'), ('TLTST', 'Tooling Testing'), ('TLMOD', 'Tooling Modification'), ('MKSMP', 'Creating Samples'), ('IMSMP', 'Improving Samples'), ('MK_WI', 'Creating WI'), ('MKBOM', 'Creatimg BOM'), ('MKECO', 'Creating ECO'), ('PRVAL', 'Process Validation'), ('PLTRN', 'Pilot Run'), ('TFBLD', 'Building Test Fixture')], max_length=5)),
                ('action_required', models.TextField()),
                ('estimated_hours', models.SmallIntegerField()),
                ('mod_date', models.DateTimeField(auto_now_add=True)),
                ('mod_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
        ),
    ]
