# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='work_type',
            field=models.CharField(choices=[('MECH', 'Mechanical'), ('ELEC', 'Electronic'), ('ASSM', 'Assembly')], max_length=4),
        ),
    ]
