# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170517_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='completed',
            new_name='is_complete',
        ),
    ]
