# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170519_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_hours',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='stage',
            field=models.CharField(choices=[('WCUST', 'Waiting for Customer Response'), ('MKDFM', 'Creating DFM'), ('TLDSN', 'Tooling Design'), ('TLBLD', 'Tooling Build'), ('TLTST', 'Tooling Testing'), ('TLMOD', 'Tooling Modification'), ('MKSMP', 'Creating Samples'), ('IMSMP', 'Improving Samples'), ('MK_WI', 'Creating WI'), ('MKBOM', 'Creating BOM'), ('MKECO', 'Creating ECO'), ('PRVAL', 'Process Validation'), ('PLTRN', 'Pilot Run'), ('TFBLD', 'Building Test Fixture')], max_length=5),
        ),
    ]
