# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170526_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='item')),
                ('responsible', models.CharField(choices=[('ENG', 'Engineering'), ('QLT', 'Quality'), ('PUR', 'Purchasing'), ('ME', 'ME'), ('PRD', 'Production'), ('PMC', 'PMC')], max_length=3, verbose_name='responsible')),
                ('completed', models.NullBooleanField(verbose_name='is complete')),
                ('remarks', models.CharField(max_length=120, verbose_name='comments')),
            ],
            options={
                'verbose_name': 'checklist item',
            },
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='remarks',
        ),
        migrations.AddField(
            model_name='milestone',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='completion date'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist', to='projects.Milestone', verbose_name='checklist'),
        ),
    ]
