# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170614_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cust_pn',
            field=models.CharField(blank=True, max_length=45, verbose_name='customer part number'),
        ),
        migrations.AddField(
            model_name='project',
            name='eastek_pn',
            field=models.CharField(blank=True, max_length=45, verbose_name='eastek part number'),
        ),
    ]
