# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170614_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='name',
            field=models.CharField(max_length=70, verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='project',
            name='engineer',
            field=models.ManyToManyField(to='employees.Employee', verbose_name='engineer(s)'),
        ),
    ]
