# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170616_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='remarks',
            field=models.CharField(blank=True, max_length=120, verbose_name='comments'),
        ),
    ]
