# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20170616_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='completed',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), (None, 'N/A')], verbose_name='is complete'),
        ),
    ]
