# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20170619_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='projects.Milestone', verbose_name='checklist'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='completed',
            field=models.NullBooleanField(choices=[(True, 'Yes'), ('False', 'No'), ('None', 'N/A')], verbose_name='is complete'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='update',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project'),
        ),
    ]
