# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20170601_0850'),
        ('projects', '0012_auto_20170621_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='estimated_hours',
        ),
        migrations.AddField(
            model_name='project',
            name='lead_eng',
            field=models.ForeignKey(default='00035', on_delete=django.db.models.deletion.PROTECT, related_name='project_leader', to='employees.Employee', verbose_name='lead engineer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='engineer',
            field=models.ManyToManyField(blank=True, related_name='project_member', to='employees.Employee', verbose_name='engineer(s)'),
        ),
        migrations.AlterField(
            model_name='update',
            name='stage',
            field=models.CharField(choices=[('RPCST', 'Responding to Customer'), ('MKDFM', 'Creating DFM'), ('TLDSN', 'Tooling Design'), ('TLBLD', 'Tooling Build'), ('TLTST', 'Tooling Testing'), ('TLMOD', 'Tooling Modification'), ('MKSMP', 'Creating Samples'), ('IMSMP', 'Improving Samples'), ('MK_WI', 'Creating WI'), ('MKBOM', 'Creating BOM'), ('MKECO', 'Creating ECO'), ('PRVAL', 'Process Validation'), ('PLTRN', 'Pilot Run'), ('TFBLD', 'Building Test Fixture')], max_length=5, verbose_name='stage'),
        ),
    ]
