# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20170718_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='deadline',
            field=models.DateField(blank=True, verbose_name='deadline'),
        ),
    ]
