# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20170719_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='deadline'),
        ),
    ]
