# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('english_name', models.CharField(max_length=40)),
                ('position', models.CharField(choices=[('AEN', 'Assistant Engineer'), ('ENG', 'Engineer'), ('SEN', 'Senior Engineer'), ('LDR', 'Engineer Leader'), ('CLK', 'Clerk'), ('TEN', 'Tooling Engineer')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('team', models.CharField(choices=[('MECH', 'Mechanical'), ('ELEC', 'Electronics'), ('SUPP', 'Support'), ('TOOL', 'Tooling')], max_length=4)),
                ('email', models.EmailField(max_length=254)),
                ('join_date', models.DateField()),
                ('ret_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
