# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.Employee'),
        ),
    ]
