# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20170420_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['emp_id']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User account'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Employed'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ret_date',
            field=models.DateField(blank=True, null=True, verbose_name='Retire date'),
        ),
    ]
