# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 02:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20170509_0623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['emp_id'], 'verbose_name': 'employee'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user account'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='english_name',
            field=models.CharField(max_length=40, verbose_name='english name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_leader',
            field=models.BooleanField(default=False, verbose_name='is leader'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(verbose_name='join date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.Employee', verbose_name='leader'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=25, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('AEN', 'Assistant Engineer'), ('ENG', 'Engineer'), ('SEN', 'Senior Engineer'), ('LDR', 'Engineer Leader'), ('CLK', 'Clerk'), ('TEN', 'Tooling Engineer')], max_length=3, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ret_date',
            field=models.DateField(blank=True, null=True, verbose_name='retire date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.CharField(choices=[('MECH', 'Mechanical'), ('ELEC', 'Electronics'), ('SUPP', 'Support'), ('TOOL', 'Tooling')], max_length=4, verbose_name='group'),
        ),
    ]
