# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20170526_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['emp_id'], 'verbose_name': 'Employee'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='employed'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.CharField(choices=[('MECH', 'Mechanical'), ('ELEC', 'Electronics'), ('SUPP', 'Support'), ('TOOL', 'Tooling')], max_length=4, verbose_name='Group'),
        ),
    ]
