# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_auto_20170420_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('request_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('reason', models.CharField(max_length=250)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=60)),
                ('customer', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='overtime',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='overtime.Projects'),
        ),
    ]
