# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import overtime.models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=60, unique=True)),
                ('customer', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='overtime',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, validators=[overtime.models.Overtime.validate_hours]),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='overtime.Project'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='reason',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='request_hours',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[overtime.models.Overtime.validate_hours]),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
