# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import overtime.models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_auto_20170424_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[overtime.models.Overtime.validate_hours]),
        ),
    ]
