# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_auto_20170424_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime', to='employees.Employee'),
        ),
    ]
