# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0004_auto_20170509_0623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtime',
            options={'permissions': (('view_Overtime', 'Can view & export overtime submissions'),)},
        ),
    ]
