# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0005_auto_20170509_0655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtime',
            options={'permissions': (('view_overtime', 'Can view & export overtime submissions'),)},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='name',
        ),
    ]
